name: test and lint
on:
   push:
      branches: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  eslint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2